//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class LearnEFEntities : DbContext
{
    public LearnEFEntities()
        : base("name=LearnEFEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Employee> Employees { get; set; }
    public virtual DbSet<tbl_shortenedUrl> tbl_shortenedUrl { get; set; }

    public virtual int SearchEmployee(string firstName, string city)
    {
        var firstNameParameter = firstName != null ?
            new ObjectParameter("FirstName", firstName) :
            new ObjectParameter("FirstName", typeof(string));

        var cityParameter = city != null ?
            new ObjectParameter("City", city) :
            new ObjectParameter("City", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SearchEmployee", firstNameParameter, cityParameter);
    }
}
